name: dl_project
channels:
  - huggingface
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.8.5
  - pandas=1.2.4
  - pytorch=1.7.1
  - torchvision=0.8.2
  - torchaudio=0.7.2
  - cudatoolkit=11.0
  - captum=0.3.1
  - jupyterlab
  - pip=20.3.3
  - pip:
    - adapter-transformers==1.1.1
    - datasets==1.5.0
    - huggingface-hub==0.0.8